############################################################
# +------------------------------------------------------+ #
# |                      威克斯日志                      | #
# |                       接手:夜政                      | #
# |                     QQ:208989395                     | #
# +------------------------------------------------------+ #
############################################################

############################################################
# +------------------------------------------------------+ #
# |                       界面配置                       | #
# +------------------------------------------------------+ #
############################################################

#gui背景图
gui: '[local]gui.png'
#按钮图片
button: '[local]button.png'
#按钮经过图片
button_hover: '[local]button_.png'
#gui偏移，-1为居中
gui-x: -1
gui-y: -1
#gui大小
gui-w: 200
gui-h: 200
gui-xs: 200
gui-ys: 200
#每行最大字数限制
#如果想主动换行请复制     这个空白字符插入到日志中
line-limit: 20
#每页行数
page-line: 16

############################################################
# +------------------------------------------------------+ #
# |                       按钮配置                       | #
# +------------------------------------------------------+ #
############################################################

#x为按钮的横坐标
#y为按钮的纵坐标
#w为按钮的宽度
#h为按钮的高度
#id为按钮的ID，不可重复。请注意，停止导航、上一页、下一页的按钮只能小于导航按钮的ID
#string为按钮的显示文字


#导航按钮配置
start-x: -35
#将会根据日志自动计算导航按钮的纵坐标，无需配置
start-w: 30
start-h: 16
start-id: 2020040499
start-string: '导航'

#停止导航按钮
stopgps-x: 203
stopgps-y: 10
stopgps-w: 42
stopgps-h: 16
stopgps-id: 2020040498
stopgps-string: '停止导航'
stopgps-command: 'gps stop'

#上一页按钮
prev-x: 203
prev-y: 35
prev-w: 42
prev-h: 16
prev-id: 2020040497
prev-string: '上一页'

#下一页按钮
next-x: 203
next-y: 60
next-w: 42
next-h: 16
next-id: 2020040496
next-string: '下一页'